"""Add documents table

Revision ID: 1c9136f8bc6f
Revises: b93e78c45a46
Create Date: 2025-11-18 10:19:51.614978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c9136f8bc6f'
down_revision = 'b93e78c45a46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
