"""add_remediation_tasks_table

Revision ID: b93e78c45a46
Revises: 53a333cb4429
Create Date: 2025-11-18 08:51:42.265854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b93e78c45a46'
down_revision = '53a333cb4429'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remediation_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_id', sa.String(length=50), nullable=True),
    sa.Column('domain', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('todo', 'in_progress', 'completed', 'cancelled', name='taskstatus'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='taskpriority'), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_domain_weights_domain'), table_name='domain_weights')
    op.drop_index(op.f('ix_domain_weights_org_id'), table_name='domain_weights')
    op.drop_constraint(op.f('uq_domain_weights_org_domain'), 'domain_weights', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_domain_weights_org_domain'), 'domain_weights', ['org_id', 'domain'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_domain_weights_org_id'), 'domain_weights', ['org_id'], unique=False)
    op.create_index(op.f('ix_domain_weights_domain'), 'domain_weights', ['domain'], unique=False)
    op.drop_table('remediation_tasks')
    # ### end Alembic commands ###
