"""Add teams table and team_id to users and assessments

Revision ID: e4862f400e22
Revises: 
Create Date: 2025-11-09 11:25:21.344243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4862f400e22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('assessments', sa.Column('team_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'assessments', 'teams', ['team_id'], ['id'])
    op.add_column('users', sa.Column('team_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'team_id')
    op.drop_constraint(None, 'assessments', type_='foreignkey')
    op.drop_column('assessments', 'team_id')
    op.drop_table('teams')
    # ### end Alembic commands ###
